package org.example.reminder_bot;
import lombok.Getter;

@Getter
public enum Country {
    USA("America/New_York", "🇺🇸"),
    India("Asia/Kolkata", "🇮🇳"),
    Japan("Asia/Tokyo", "🇯🇵"),
    Germany("Europe/Berlin", "🇩🇪"),
    Brazil("America/Sao_Paulo", "🇧🇷"),
    Australia("Australia/Sydney", "🇦🇺"),
    Canada("America/Toronto", "🇨🇦"),
    China("Asia/Shanghai", "🇨🇳"),
    France("Europe/Paris", "🇫🇷"),
    Russia("Europe/Moscow", "🇷🇺"),
    UnitedKingdom("Europe/London", "🇬🇧"),
    SouthAfrica("Africa/Johannesburg", "🇿🇦"),
    SouthKorea("Asia/Seoul", "🇰🇷"),
    Italy("Europe/Rome", "🇮🇹"),
    Spain("Europe/Madrid", "🇪🇸"),
    Turkey("Europe/Istanbul", "🇹🇷"),
    Egypt("Africa/Cairo", "🇪🇬"),
    NewZealand("Pacific/Auckland", "🇳🇿"),
    Indonesia("Asia/Jakarta", "🇮🇩"),
    SaudiArabia("Asia/Riyadh", "🇸🇦"),
    Pakistan("Asia/Karachi", "🇵🇰"),
    Nigeria("Africa/Lagos", "🇳🇬"),
    Poland("Europe/Warsaw", "🇵🇱"),
    Netherlands("Europe/Amsterdam", "🇳🇱"),
    Sweden("Europe/Stockholm", "🇸🇪"),
    Norway("Europe/Oslo", "🇳🇴"),
    Finland("Europe/Helsinki", "🇫🇮"),
    Switzerland("Europe/Zurich", "🇨🇭"),
    Belgium("Europe/Brussels", "🇧🇪"),
    Austria("Europe/Vienna", "🇦🇹"),
    Denmark("Europe/Copenhagen", "🇩🇰"),
    Argentina("America/Argentina/Buenos_Aires", "🇦🇷"),
    Chile("America/Santiago", "🇨🇱"),
    Peru("America/Lima", "🇵🇪"),
    Colombia("America/Bogota", "🇨🇴"),
    Venezuela("America/Caracas", "🇻🇪"),
    Ukraine("Europe/Kiev", "🇺🇦"),
    CzechRepublic("Europe/Prague", "🇨🇿"),
    Slovakia("Europe/Bratislava", "🇸🇰"),
    Hungary("Europe/Budapest", "🇭🇺"),
    Romania("Europe/Bucharest", "🇷🇴"),
    Bulgaria("Europe/Sofia", "🇧🇬"),
    Serbia("Europe/Belgrade", "🇷🇸"),
    Croatia("Europe/Zagreb", "🇭🇷"),
    Slovenia("Europe/Ljubljana", "🇸🇮"),
    BosniaAndHerzegovina("Europe/Sarajevo", "🇧🇦"),
    Montenegro("Europe/Podgorica", "🇲🇪"),
    Albania("Europe/Tirane", "🇦🇱"),
    NorthMacedonia("Europe/Skopje", "🇲🇰"),
    Kosovo("Europe/Pristina", "🇽🇰"),
    Moldova("Europe/Chisinau", "🇲🇩"),
    Georgia("Asia/Tbilisi", "🇬🇪"),
    Armenia("Asia/Yerevan", "🇦🇲"),
    Belarus("Europe/Minsk", "🇧🇾"),
    Kyrgyzstan("Asia/Bishkek", "🇰🇬"),
    Uzbekistan("Asia/Tashkent", "🇺🇿"),
    Turkmenistan("Asia/Ashgabat", "🇹🇲"),
    Kazakhstan("Asia/Almaty", "🇰🇿"),
    Azerbaijan("Asia/Baku", "🇦🇿"),
    Kuwait("Asia/Kuwait", "🇰🇼"),
    Qatar("Asia/Qatar", "🇶🇦"),
    UnitedArabEmirates("Asia/Dubai", "🇦🇪"),
    Oman("Asia/Muscat", "🇴🇲"),
    Bahamas("America/Nassau", "🇧🇸"),
    Barbados("America/Barbados", "🇧🇧"),
    Jamaica("America/Jamaica", "🇯🇲"),
    TrinidadAndTobago("America/Port_of_Spain", "🇹🇹"),
    Guyana("America/Guyana", "🇬🇾"),
    Belize("America/Belize", "🇧🇿"),
    Honduras("America/Tegucigalpa", "🇭🇳"),
    Guatemala("America/Guatemala", "🇬🇹"),
    CostaRica("America/Costa_Rica", "🇨🇷"),
    Nicaragua("America/Managua", "🇳🇮"),
    ElSalvador("America/El_Salvador", "🇸🇻"),
    Panama("America/Panama", "🇵🇦"),
    Cuba("America/Havana", "🇨🇺"),
    DominicanRepublic("America/Santo_Domingo", "🇩🇴"),
    Ecuador("America/Guayaquil", "🇪🇨"),
    Paraguay("America/Asuncion", "🇵🇾"),
    Bolivia("America/La_Paz", "🇧🇴"),
    Suriname("America/Paramaribo", "🇸🇷"),
    FrenchGuiana("America/Cayenne", "🇬🇫"),
    SaintLucia("America/St_Lucia", "🇱🇨"),
    SaintKittsAndNevis("America/St_Kitts", "🇰🇳"),
    SaintVincentAndGrenadines("America/St_Vincent", "🇻🇨"),
    AntiguaAndBarbuda("America/Antigua", "🇦🇬"),
    SaintPierreAndMiquelon("America/Miquelon", "🇵🇲"),
    Greenland("America/Nuuk", "🇬🇱"),
    Iceland("Atlantic/Reykjavik", "🇮🇸"),
    FaroeIslands("Atlantic/Faeroe", "🇫🇴");

    private final String timeZone;
    private final String flag;

    Country(String timeZone, String flag) {
        this.timeZone = timeZone;
        this.flag = flag;
    }

}


